// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITpAEzrMkTOtgLcRQBYoddFmHlXU8LDY',
    appId: '1:347366385644:web:72845b7da5911eaa4b42c9',
    messagingSenderId: '347366385644',
    projectId: 'crud-firebase-bbafa',
    authDomain: 'crud-firebase-bbafa.firebaseapp.com',
    storageBucket: 'crud-firebase-bbafa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmkWVPfEIBYblCU0ARbQOjEkT_10zK-sc',
    appId: '1:347366385644:android:87ce1fe782affa8f4b42c9',
    messagingSenderId: '347366385644',
    projectId: 'crud-firebase-bbafa',
    storageBucket: 'crud-firebase-bbafa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCovMAigWM4ISoNWtgadifL1H-4oNzxcLY',
    appId: '1:347366385644:ios:e83df554685bc0324b42c9',
    messagingSenderId: '347366385644',
    projectId: 'crud-firebase-bbafa',
    storageBucket: 'crud-firebase-bbafa.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCovMAigWM4ISoNWtgadifL1H-4oNzxcLY',
    appId: '1:347366385644:ios:e83df554685bc0324b42c9',
    messagingSenderId: '347366385644',
    projectId: 'crud-firebase-bbafa',
    storageBucket: 'crud-firebase-bbafa.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDITpAEzrMkTOtgLcRQBYoddFmHlXU8LDY',
    appId: '1:347366385644:web:895c285e60b3f1084b42c9',
    messagingSenderId: '347366385644',
    projectId: 'crud-firebase-bbafa',
    authDomain: 'crud-firebase-bbafa.firebaseapp.com',
    storageBucket: 'crud-firebase-bbafa.appspot.com',
  );
}
